@startuml

enum DeviceStatus {
  AVAILABLE
  BROKEN
  MAINTENANCE
  IN_USE
}

enum DeviceType{
  ROUTER
  SWITCH
  ACCESS_POINT
}

enum UserRole {
  TECHNICIAN
  CEO
  ADMIN
}


abstract class User {
  - int id
  - String login
  - String password
  - UserRole role
  + login()
  + logout()
}

class Technician extends User {
  + addDevice(BusinessManager, Device)
  + removeDevice(BusinessManager, Device)
  + connectDevices(BusinessManager, Device, Device)
  + changeDeviceConfig(Device)
}

class CEO extends User {
  + makeReport(BusinessManager)
  + viewInventory(BusinessManager)
}

class Admin extends User {
  + blockUser(User)
  + registerUser(User)
}

class Device {
  - Long id
  - DeviceType type
  - DeviceStatus status
  - String model
  - String hostName
  - int numberOfEthInterfaces
  - String configuration
  + getId(): Long
  + getType(): DeviceType
  + setType(DeviceType type): void
  + getStatus(): DeviceStatus
  + setStatus(DeviceStatus status): void
  + getModel(): String
  + setModel(String model): void
  + getHostName(): String
  + setHostName(String hostName): void
  + getNumberOfEthInterfaces(): int
  + setNumberOfEthInterfaces(int number): void
  + getConfiguration(): String
  + setConfiguration(String configuration): void
}

class DeviceDAO {
  - static DeviceDAO instance
  - Connection dbConnection
  - DeviceDAO()
  + static getInstance(): DeviceDAO
  + save(Device device): void
  + findById(Long id): Device
  + findAll(): List<Device>
  + update(Device device): void
  + deleteById(Long id): void
}

DeviceDAO ..> Device : uses

class BusinessManager {
  - BusinessManager instance
  - List<Device> inventory
  - List<User> users
  + BusinessManager()
  + getInstance()
}
BusinessManager "1" *-- "*" Device
BusinessManager "1" *-- "*" User

@enduml