package pl.edu.agh.po.service;

import pl.edu.agh.po.dao.DeviceDAO;
import pl.edu.agh.po.dao.UserDAO;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class ReportService {
    private static ReportService instance;

    private ReportService(){}

    public static ReportService getInstance(){
        if (instance == null){
            instance = new ReportService();
        }
        return instance;
    }

    public String generateFullRaport(){
        StringBuilder raport = new StringBuilder();
        
        raport.append("# Full RouterPOL raport");
        raport.append("generated at: ").append(LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"))).append("\n");
        raport.append("generated by:").append(AuthenticationService.getInstance().getCurrentUser().getUsername()).append("\n");
        raport.append("─".repeat(65)).append("\n\n");
        raport.append("## Numbers summary\n");
        raport.append("There is: ").append(UserDAO.getInstance().findALL().size()).append(" registered users.\n");
        raport.append("There is: ").append(DeviceDAO.getInstance().findAll().size()).append(" devices.\n");
        raport.append("─".repeat(65)).append("\n");
        
        return raport.toString();
    }
}
