package pl.edu.agh.po.service;

import pl.edu.agh.po.dao.DeviceDAO;
import pl.edu.agh.po.dao.UserDAO;
import pl.edu.agh.po.model.Device;
import pl.edu.agh.po.model.DeviceType;
import pl.edu.agh.po.model.DeviceStatus;
import pl.edu.agh.po.model.User;
import pl.edu.agh.po.model.UserRole;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class ReportService implements ReportManager{
    private static ReportService instance;

    private ReportService(){}

    public static ReportService getInstance(){
        if (instance == null){
            instance = new ReportService();
        }
        return instance;
    }

    public String generateFullRaport(){
        StringBuilder raport = new StringBuilder();
        List<Device> devices = DeviceDAO.getInstance().findAll();
        List<User> users = UserDAO.getInstance().findALL();

        raport.append("# Full RouterPOL raport\n");
        raport.append("generated at: ").append(LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"))).append("\n");
        raport.append("generated by: ").append(AuthenticationService.getInstance().getCurrentUser().getUsername()).append("\n");
        raport.append("─".repeat(65)).append("\n\n");
        raport.append("## Numbers summary\n");
        raport.append("There is: ").append(users.size()).append(" registered users.\n");
        raport.append("There is: ").append(devices.size()).append(" devices.\n");
        raport.append("─".repeat(65)).append("\n\n");

        raport.append("## Devices by type\n");
        Map<DeviceType, Long> devicesByType = devices.stream().collect(Collectors.groupingBy(Device::getType, Collectors.counting()));
        raport.append("Routers: ").append(devicesByType.getOrDefault(DeviceType.ROUTER, 0L)).append("\n");
        raport.append("Switches: ").append(devicesByType.getOrDefault(DeviceType.SWITCH, 0L)).append("\n");
        raport.append("Access Points: ").append(devicesByType.getOrDefault(DeviceType.ACCESS_POINT, 0L)).append("\n");
        raport.append("─".repeat(65)).append("\n\n");

        raport.append("## Devices by status\n");
        Map<DeviceStatus, Long> devicesByStatus = devices.stream().collect(Collectors.groupingBy(Device::getStatus, Collectors.counting()));
        raport.append("Available: ").append(devicesByStatus.getOrDefault(DeviceStatus.AVAILABLE, 0L)).append("\n");
        raport.append("In Use: ").append(devicesByStatus.getOrDefault(DeviceStatus.IN_USE, 0L)).append("\n");
        raport.append("Maintenance: ").append(devicesByStatus.getOrDefault(DeviceStatus.MAINTANCE, 0L)).append("\n");
        raport.append("Broken: ").append(devicesByStatus.getOrDefault(DeviceStatus.BROKEN, 0L)).append("\n");
        raport.append("─".repeat(65)).append("\n\n");

        raport.append("## Devices list\n");
        for (Device device : devices) {
            raport.append("ID: ").append(device.getId()).append(" | ");
            raport.append(device.getHostName()).append(" | ");
            raport.append(device.getType()).append(" | ");
            raport.append(device.getStatus()).append(" | ");
            raport.append(device.getModel()).append(" | ");
            raport.append("Interfaces: ").append(device.getNumberOfEthernetInterfaces()).append("\n");
        }
        raport.append("─".repeat(65)).append("\n\n");

        raport.append("## Users by role\n");
        Map<UserRole, Long> usersByRole = users.stream().collect(Collectors.groupingBy(User::getRole, Collectors.counting()));
        raport.append("Admins: ").append(usersByRole.getOrDefault(UserRole.ADMIN, 0L)).append("\n");
        raport.append("CEOs: ").append(usersByRole.getOrDefault(UserRole.CEO, 0L)).append("\n");
        raport.append("Technicians: ").append(usersByRole.getOrDefault(UserRole.TECHNICIAN, 0L)).append("\n");
        raport.append("─".repeat(65)).append("\n\n");

        raport.append("## Security summary\n");
        long usersWithTotp = users.stream().filter(User::isTotpEnabled).count();
        raport.append("Users with 2FA enabled: ").append(usersWithTotp).append(" / ").append(users.size()).append("\n");
        raport.append("─".repeat(65)).append("\n");

        return raport.toString();
    }
}
