package pl.edu.agh.po;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class BusinessManager {
    private static BusinessManager instance;

    private BusinessManager(){}

    public static BusinessManager getInstance(){
        if (instance == null){
            instance = new BusinessManager();
        }
        return instance;
    }

    public String generateFullRaport(){
        StringBuilder raport = new StringBuilder();
        
        raport.append("# Full RouterPOL raport");
        raport.append("generated at: ").append(LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"))).append("\n");
        raport.append("generated by:").append(AuthenticationService.getInstance().getCurrentUser().getUsername()).append("\n");
        raport.append("─".repeat(65)).append("\n\n");
        raport.append("## Numbers summary\n");
        raport.append("There is: ").append(UserDAO.getInstance().findALL().size()).append(" registered users.\n");
        raport.append("There is: ").append(DeviceDAO.getInstance().findAll().size()).append(" devices.\n");
        raport.append("─".repeat(65)).append("\n");
        
        return raport.toString();
    }
}
